---
title: "FAQ - Variable Definitions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FAQ - Variable Definitions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

In this article, we listed frequently asked questions regarding how we defined the variables in our medicare analytic files. it's working in progress document, since the definitions can change, and new variables can be added.

In our medicare analytic files, variables come from two sources:

-   CMS original files (e.g. patient gender, procedure date, etc.)
-   Derived variables (e.g. readmission, multi-procedure, etc.).

In this document, we focused on derived variables.

## Variable Definitions

### 30-day Severe complication (no POA)

Severe complication excluding POA was defined as having one or more complications from the list below within 30 days after the index procedure, and the length of stay is greater than 75% of the cases for the procedure group. For example, a severe complication after Partial Colectomy is having any complication from the list below within 30 days after the procedure, and the hospoital length of stay is more than 75% of medicare patients stayed for Partial Colectomy procedures.

```{.r}
[1] "post-op lung failure" 
[2] "post-op pneumonia"    
[3] "post-op MI"           
[4] "post-op dvt/pe"       
[5] "post-op renal failure"
[6] "post-op hemorrhage"   
[7] "post-op ssi"          
[8] "post-op GI hemorrhage"
```


### 30-day Reoperation

Reoperation is one of the major patient outcomes, and often used in our medicare outcome analysis. We define reoperation by 1. Looking through the procedure codes across multiple admissions; 2. Create the ICD9/10 procedure codes to re-operation mapping using pre-defined operation types; 3. Get the re-operation flags if defined re-operation happened within \<=30 days; 4. emergent admission

8 operations were included in the re-operation mapping below. All the operations were defined using ICD9/10 code in MedPAR

``` {.r}
[1] "Reoperation for management of deep surgical site infection"  
[2] "Retrieval of retained foreign body"                        
[3] "Management of postoperative shock/hemorrhage"              
[4] "Management of stoma complications"                         
[5] "Management of wound complication"                          
[6] "Reclosure of dehiscence"                                   
[7] "Reopening of surgical site"                                
[8] "Repair of an organ injury/laceration"
```

Reoperations were from all MedPAR claims, which include all procedures in Medicare, not just the procedures we study.

### 30-day Readmission

readmission to emergent inpatient admission within 30 days of the index procedure

### multi-surgeon

multiple providers (not necessary to be surgeons, for example providers can be PA) operated in one hospital admission. It can be different procedures. For example, if one patient in *one hospital admission* had both Partial Colectomy and Cholecystectomy by different NPI, both the Cole and the Cholecystectomy procedures were flagged as multi-surgeon.

``` {.r}
original_data %>%
    distinct(
      member_id,
      dt_facclm_adm,     # facility claim admission date
      dt_facclm_dschg,   # facility claim discharge date
      id_physician_npi
    ) %>%
    add_count(member_id,
              dt_facclm_adm,
              dt_facclm_dschg,
              name = "n_doc"   # n_doc>1 was defined as multi-surgeon
    )
```

### assistant_surgeon

Assistant surgeon role was defined by CPT modifier code "80" or "82". So if a case has either "80" or "82" as the CPT modifier, then it is flagged as assistant_surgeon case.

``` {.r}
flg_assistant_surgeon = ifelse(str_detect(cpt_mod, "80|82"), 1, 0)
```

### multi_cpt

Multiple CPT was defined as one patient has multiple CPTs performed in one hospital admission. Note CPT modifier code is not in cosideration here.

``` {.r}
data %>%
    distinct(
      member_id,
      dt_facclm_adm,     # facility claim admission date
      dt_facclm_dschg,   # facility claim discharge date
      cpt_cd             # CPT code
    ) %>%
    add_count(member_id,
              dt_facclm_adm,
              dt_facclm_dschg,
              name = "n_proc"
    ) 
```

### POA

Present on admission flag. Any complication and severe complication are defined by complications that were not POA. However, the POA flag is not available in MedPAR before 2010. So, any analyses related to complication using medicare analytic file starts from 2010.

One note, in RedDAC website, it states [POA](https://resdac.org/cms-data/variables/claim-diagnosis-code-i-diagnosis-present-admission-poa-indicator-code-ffs) was was not available until 2011. However, I double checked with our actual dataset, POA variables started in 2010.
